---
# this comment prevents git conflicts
cf-rabbitmq-multitenant-broker-golang/go1.25.2.linux-amd64.tar.gz:
  size: 59766306
  object_id: 11965438-8907-45e2-5641-d445917685ed
  sha: sha256:d7fa7f8fbd16263aa2501d681b11f972a5fd8e811f7b10cb9b26d031a3d7454b
