---
# this comment prevents git conflicts
cf-rabbitmq-multitenant-broker-golang/go1.25.5.linux-amd64.tar.gz:
  size: 59768009
  object_id: e62c7efe-643a-41a0-76c4-e71621bb307b
  sha: sha256:9e9b755d63b36acf30c12a9a3fc379243714c1c6d3dd72861da637f336ebb35b
