---
# this comment prevents git conflicts
cf-rabbitmq-multitenant-broker-golang/go1.26.0.linux-amd64.tar.gz:
  size: 66768540
  object_id: 39a13641-45d0-4e54-533e-e161f3369703
  sha: sha256:aac1b08a0fb0c4e0a7c1555beb7b59180b05dfc5a3d62e40e9de90cd42f88235
