# this comment prevents git conflicts
cf-rabbitmq-multitenant-broker-golang/go1.25.1.linux-amd64.tar.gz:
  size: 59660846
  object_id: 855b36ce-28ae-45b8-727c-b3f7db8d8033
  sha: sha256:7716a0d940a0f6ae8e1f3b3f4f36299dc53e31b16840dbd171254312c41ca12e
# this comment prevents git conflicts
cf-rabbitmq-multitenant-broker-golang/go1.25.4.linux-amd64.tar.gz:
  size: 59766394
  sha: sha256:9fa5ffeda4170de60f67f3aa0f824e426421ba724c21e133c1e35d6159ca1bec
